# Generated by Django 4.0.4 on 2022-05-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_sent_at', models.DateTimeField(blank=True)),
                ('title', models.CharField(default='title', max_length=100)),
                ('type', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('WARNING', 'WARNING'), ('FAIL', 'FAIL')], default='SUCCESS', max_length=100)),
                ('content', models.CharField(blank=True, default='content', max_length=100)),
            ],
        ),
    ]
